FROM alpine:3.22

RUN apk add --no-cache ca-certificates tzdata
WORKDIR /app

ARG TARGETARCH

COPY bin/${TARGETARCH}/rs-cmdb-server ./rs-cmdb-server
COPY dist ./dist

RUN chmod +x ./rs-cmdb-server

EXPOSE 8080
CMD ["./rs-cmdb-server"]